### ISSUE TITLE
word_count_weight and valid_word_count_weight

### ISSUE THREAD

**Issue by jinserk** [parlance/pytorch-ctc#15]
Hi, I cannot still understand the word_count_weight and valid_word_count_weight. What they affect to the scoring? I've found that each default value is 0. and 1. in ctc_beam_scorer_klm.h

**Comment by ryanleary** [comment]
`word_count_weight` is a word-insertion bonus factor. `valid_word_count_weight` is the same thing, but only applies if the word is within the supplied dictionary. See http://deeplearning.stanford.edu/lexfree/lexfree.pdf
