### ISSUE TITLE
import pytorch_ctc error

### ISSUE THREAD

**Issue by bliunlpr** [parlance/pytorch-ctc#8]
I have installed pytorch_ctc，but got the import error.

>>> from pytorch_ctc import CTCBeamDecoder as CTCBD
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bliu/anaconda3/lib/python3.5/site-packages/pytorch_ctc/__init__.py", line 4, in <module>
    from ._ctc_decode import lib as _lib, ffi as _ffi
ImportError: /home/bliu/anaconda3/lib/python3.5/site-packages/pytorch_ctc/_ctc_decode.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

**Comment by ryanleary** [comment]
Can you tell me what compiler is used and which version of libstdc++?

**Comment by bliunlpr** [comment]
I  used CC=/usr/bin/gcc-5 CXX=/usr/bin/g++-5 python setup.py install. 
I have no idea which version of libstdc++.  How can I check this ?  Thanks!

**Comment by SiddGururani** [comment]
I got a similar error but then I rebuilt using `sudo` and it worked. Not very insightful but give it a shot if you've not already done so.

**Comment by ryanleary** [comment]
I think the recent build changes should solve this.
